#default: &default
#    adapter: mysql2
#    encoding: utf8
#    reconnect: false
#    username: root
#    password:
#    socket: /tmp/mysql.sock
#
#  development:
#    <<: *default
#    database: [アプリ名]_development
#    pool: 5
#    timeout: 5000
#    host: localhost
#
#  test:
#    <<: *default
#    database: [アプリ名]_test
#    pool: 5
#    timeout: 5000
#    host: localhost
#
#  production:
#    <<: *default
#    database: [アプリ名]_production
#    pool: 5
#    timeout: 5000
#    host: localhost


default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: false
  username: root
  password:
  socket: /tmp/mysql.sock
  host: localhost

development:
  <<: *default
  database: sample_development
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: sample_test
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: sample_production
  pool: 5
  timeout: 5000

